-- print("^2Jim^7-^2Recycle v^42^7.^45 ^7- ^2Recycling Script by ^1Jimathy^7")

Config = {
	Lan = "en",
	Debug = false, -- Toggle Debug Mode
	Blips = true, -- Enable Blips?
	BlipNamer = false, -- Enable to Name Blips different things, disable if you already have too many blips as this will group them together
	Pedspawn = true, -- Do you want to spawn peds for main locations?
	img = "qb-inventory/html/images/", -- Set this to your inventory
	JimMenu = false, -- If using updated qb-menu icons, set this true
	JobRole = nil, -- Whats the job role you want to use this? "nil" for none
	EnableOpeningHours = false, -- Enable opening hours? If disabled you can always open the pawnshop.
	OpenHour = 9, -- From what hour should the pawnshop be open?
	CloseHour = 21, -- From what hour should the pawnshop be closed?
	PayAtDoor = nil, -- Set to nil stop turn this off, set to a number to enable

	Minigame = "qb-lock", -- Enable minigame when searching. qb-skillbar/qb-lock/ps-ui

	OutsideTele = vector4(746.83, -1399.66, 26.6, 230.732),
	InsideTele = vector4(993.16, -3097.61, -39.90, 82.95),

	Locations =  {
		['Recycle'] = {
			{ name = "Recycle Center", coords = vector4(744.68, -1401.77, 26.55, 248.73), blipTrue = true, sprite = 365, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
		},
		['Trade'] ={
			{ name = "Recyclable Trader", coords = vector4(997.48, -3097.44, -39.0, 234.53), blipTrue = false, sprite = 365, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
		},
		['BottleBanks'] = {
			--{ name = "Bottle Bank", coords = vector4(757.06, -1399.68, 26.57 , 178.1), blipTrue = false, sprite = 642, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
			{ name = "Bottle Bank", coords = vector4(84.01, -220.32, 54.64 , 337.89), blipTrue = false, sprite = 642, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
			{ name = "Bottle Bank", coords = vector4(31.88, -1315.58, 29.52 , 357.19), blipTrue = false, sprite = 642, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
			{ name = "Bottle Bank", coords = vector4(29.08, -1769.99, 29.61 , 50.0), blipTrue = false, sprite = 642, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
			{ name = "Bottle Bank", coords = vector4(394.08, -877.48, 29.35 , 310.12), blipTrue = false, sprite = 642, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
			{ name = "Bottle Bank", coords = vector4(-1267.97, -812.08, 17.11 , 128.12), blipTrue = false, sprite = 642, col = 2, model = `G_M_M_ChemWork_01`, scenario = "WORLD_HUMAN_CLIPBOARD", },
		},
	},
	Prices = {
		['copper'] = 30,
		['plastic'] = 30,
		['metalscrap'] = 30,
		['plastic'] = 30,
		['glass'] = 30,
		['iron'] = 30,
		['rubber'] = 30,
		['aluminum'] = 30,
		['bottle'] = 30,
		['can'] = 30,
	},
	TradeTable = {
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		--rare items
		"aluminumoxide",
		"electronickit",
		"cryptostick",
		
		"plasma_cutter",
	},
	DumpItems = {
		"cryptostick",
		"burnerphone",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"bottle",
		"blue_coloring",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plasticjerrycan",
		"plasticjerrycan",
		"plasticjerrycan",
		"plasticjerrycan",
		"plasticjerrycan",
		"plasticjerrycan",
		"can",
		"can",
		"can",
		"can",
		"can",
		"can",
		"can",
		"can",
		"benzocaine",
		"benzocaine",
		"benzocaine",
		"benzocaine",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"plastic",
		"rubber",
		"screwdriver",
		"screwdriver",
		"lockpick",
		"screwdriver",
		"lockpick",
		"meth_amoniak",
		"meth_amoniak",
		"rustytool",
		"rustytool",
		"lockpick",
		"screwdriver",
	 	"rustytool",
		 "glass",
		 "lockpick",
		 "meth_amoniak",
		 "glass",
		 "glass",
		 "glass",
		 "metalscrap",
		 "metalscrap",
		 "cigarett",
		 "cigarett",
		 "cigarett",
		 "cigarett",
		 "cigarett",
		 "cigarett",
		 "meth_amoniak",
		 "cigarett",
		 "cigarett",
		 "cigarett",
		 "gunpowder",
		 "gunpowder",
		 "sterilewater",
		 "weapon_switchblade",
		"bandage",
		"bandage",
		"lsd1",
		"meth_pipe",
		"crack_pipe",
		"ecstasy1",
		"ecstasy2",
		"blue_phone",
		"walkstick",
		"meth",
		"liquidheroin",
		"heroin_syringe",
		"spring",
		"painkillers",
		"binoculars",
		"lighter",
		"ducttape",
		  "lockpick",
		   "advancedlockpick",
		    "electronickit",
        "weapon_hammer", 
		"plastic", 
		"painkillers", 
		"can", 
		"metalscrap",
		  "crack_pipe",
		   "heroin_syringe", 
		 "sim_card",
		"heroinbaggy", 

        

	},
	
	ScrapItems = {
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		"copper",
		"plastic",
		"metalscrap",
		"plastic",
		"glass",
		"iron",
		"rubber",
		"aluminum",
		"bottle",
		"can",
		"copperwire",
		--rare items
		"aluminumoxide",
		"electronickit",
		"cryptostick",
		
		"plasma_cutter",
		"can",

		
	},
	RecycleAmounts = {
		recycleMin = 3,
		recycleMax = 5,

		tenMin = 30,
		tenMax = 50,

		hundMin = 300,
		hundMax = 500,

		thouMin = 10,
		thouMax = 28,
	}
}

Loc = {}
